driver:
  name: terraform
  variables:
    ami_values: placeholder
  root_module_directory: test/fixtures

provisioner:
  name: terraform

platforms:
  - name: aws

verifier:
  name: terraform
  systems:
  - name: aws_cloud
    backend: aws
    controls:
      - aws_cloud_resources

  - name: os_checks
    backend: ssh
    hosts_output: promtheus_server_ip
    sudo: true
    key_files:
      - ~/Downloads/djeche-insecure-new.pem
    controls:
      - operating_system
    user: ubuntu

suites:
  - name: prometheus_aws

